site_name: Estatística++
theme:
  name: material
  logo: assets/estatisticamaismais_logo_branco_transparente.png
  favicon: assets/estatisticamaismais_logo.png
  features:
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
